### ISSUE TITLE
[Mega-Issue] New Codegen

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#1700]
This Mega-Issue helps summarize and link to all the various things we're working on around New Codegen for high-level planning purposes. This issue will be updated as things change. Please open any comments on more specific issues, or file a new issue. Thank you!

### Previously on New Codegen
#939 was an RFC proposing a new format for generated code, along with the steps to get us off having code generated by our typescript CLI. 

### The Good News
The process #939 outlined is going to be basically the same: Get codegen working without caching, add immutable caching, add mutable caching, remove old caching. 

### The Medium News
We were initially anticipating either continuing to do parsing and validation with the existing JS CLI or with our Rust CLI. We're going to be deprecating the first and the second has a different focus, but we have found a workaround: Using GraphQL-JS wrapped in [`JavaScriptCore`](https://nshipster.com/javascriptcore/), which means no dependencies, and more importantly, no NPM. 

### The Bad News 
After over a year of various people banging their heads on it, the expected code presented in #939 is ultimately unworkable. The biggest issue, sadly, is that Fragments As Protocols is basically impossible to make usable with _any_ nested types given Swift's lack of support for covariance. 

You know how you hate the warning that says that you can't use something as a generic constraint because it has self or associated type requirements? Believe me, no matter how much you hate it, I hate it more. 

Once we realized we couldn't represent fragments as protocols, this broke a bunch of other assumptions, particularly around trying not to duplicate data. @AnthonyMDev has been heads down working on a new solution and is making progress, but there's still a lot of things up in the air. There will be an updated RFC once we've got something we're internally happy with, but this has very much been a two steps forward, two steps back problem. 

### The plan!

Here is the rough outline of what we're going to be working on: 

- [ ] Create new desired generated code
- [x] Use `JavascriptCore` to take advantage of GraphQL-JS's parsing and validation without the need for NPM.
- [ ] Use `JavascriptCore` it to generate an intermediate representation we can use to generate swift code
- [ ] Consume intermediate representation from JS to actually generate Swift code using Swift code. 
- [ ] Proceed with the rest of the plan in #939. 

### Bugs in the existing implementation we want to fix

- [x] #1133, #955 Pluralization makes some weird choices that can't be overridden
- [ ] #126, #184 Better handling of fragment and its field having the same name.
- [ ] #72, #463 Capitalization is not respected
- [ ] #843, #1222 Occasionally parameter or enum case order is nondeterministic
- [ ] #562 Make sure documentation is added wherever we have it from the schema
- [ ] #1077, #1207 Everything is turned into `camelCase` even if the `camelCase` and `snake_case` properties are two different things or it makes things unreadable
- [x] #1678 `@include`/`@skip` directives are not taken into account when deciding if a fragment should be optional

### New features we're definitely doing

- [x] #149 Support for types being marked as `internal` rather than public (or not marked at all). 
- [ ] #611 Add public initializers for all objects to facilitate easier mocking
- [ ] #212 Include GraphQL default variables in generated code
- [ ] #720 Failure to parse properties for unknown type leads to a crash
- [ ] #710 `Identifiable` support at least for objects with an `id` property

### New features we hope to do, but maybe not immediately

- [ ] #636 Prevent re-running codegen if queries haven't changed
- [ ] #1047 Splitting out types necessary for codegen into `ApolloCore` so generated code doesn't have to import the whole `Apollo` lib
- [ ] #442 Baked-in `Equatable` support 
- [x] #467 `Codable` support
- [ ] #1083 Output code in relative directories

### New features we will definitely do, but not right now 

- [ ] #1087 Generating code across multiple modules
- [ ] [issue TBA] Support for generating `Identifiable` conformance based on directives on either the schema or queries

**Comment by kaushik143** [comment]
I am facing a similar issue when I am trying to migrate to apollo-v2. Is there any suggestion available for this to allow null value for this kind of variable?

**Comment by calvincestari** [comment]
Superseded by the [1.0 codegen proposal](https://github.com/apollographql/apollo-ios/blob/release/1.0/CodegenProposal.md).
