### ISSUE TITLE
[Mega-Issue] Cache Improvements 

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-ios#1701]
This Mega-Issue helps summarize and link to all the various things we're working on around improvements to the cache for high-level planning purposes. This issue will be updated as things change. Please open any comments on more specific issues, or file a new issue. Thank you!

Note: New issues will likely be added as we finish up our new codegen, since changes may be needed to make that work.  

### New features we're definitely doing

- [ ] #142 Cache eviction and expiration
- [ ] [issue TBA] Better handling of paginated data
- [ ] #1568 Add field-level metadata to facilitate expiration
- [ ] #1304 Better testing for generating keys from dynamic objects

### Bugs we want to fix

- [ ] #1071 Cache key separator shouldn't be `.` because it interferes with properties with a period in them (such as filenames)
- [ ]  #516, #678 `GraphQLWatcher` retain cycle handling 
- [ ] #99 Better handling of callbacks when first starting a watcher
- [ ] #1683 huge amounts of memory used when parsing huge queries into the cache

### New features we hope to do, but maybe not immediately

- [  ] #1196 Optimistic Caching & rollbacks
- [  ] #884 add option to refetch queries after a mutation
- [ ] #565 fetch more for paginated requests

### New features we would like to do, but not right now

- [ ] #197 Propagating errors to the field which caused them
- [ ] [Issue TBA] Ability to chain different caches (ex, In-memory as primary, SQLite as fallback)
