### ISSUE TITLE
iOS 1.0 GA Blog

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-ios#2355]
As part of our Go to market approach for the iOS 1.0 release, we'll be writing a blog that focuses on the cool stuff in the 1.0 release. 

###  Tasks

- [ ] Draft Blog Outline
- [ ] Draft Blog content
- [ ] Review with key stakeholders
- [ ] Launch Blog

**Comment by jpvajda** [comment]
I have a draft of the blog ready for review, I'll share with the team for feedback.

**Comment by jpvajda** [comment]
the post can be found here:  https://www.apollographql.com/blog/mobile/ios/apollo-ios-client-1-0-with-improved-code-generation/
